- hosts: web
  gather_facts: false
  connection: aws_ssm

  tasks:
    - name: Install nginx
      command: yum install -y nginx

    - name: Deploy index.html to NGINX default root
      shell: |
        cat << 'EOF' > /usr/share/nginx/html/index.html
        {{ lookup('file', './index.html') }}
        EOF
    
    - name: Enable nginx
      command: systemctl enable nginx

    - name: Start nginx
      command: systemctl start nginx
