- hosts: web
  gather_facts: false
  connection: aws_ssm

  tasks:
    - name: Install nginx
      raw: yum install -y nginx

    - name: Enable nginx
      raw: systemctl enable nginx

    - name: Start nginx
      raw: systemctl start nginx

    - name: Deploy index.html from repo
      raw: |
        cat << 'EOF' > /usr/share/nginx/html/index.html
        {{ lookup('file', './index.html') }}
        EOF
